version: 2
updates:

  # Maven (backend)
  - package-ecosystem: "maven"
    directory: "/backend/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    groups:
      maven-minor-patch:
        update-types:
          - "minor"
          - "patch"
    labels:
      - "dependencies"
      - "backend"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    groups:
      github-actions:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "ci"