apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sdfcc-backend.fullname" . }}-config
  labels:
    {{- include "sdfcc-backend.labels" . | nindent 4 }}
{{- if .Values.config }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- else }}
data: {}
{{- end }}
