{{- if and .Values.secret.enabled (not .Values.secret.existingSecretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sdfcc-backend.secretName" . }}
  labels:
    {{- include "sdfcc-backend.labels" . | nindent 4 }}
type: Opaque
{{- if .Values.secret.data }}
stringData:
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- else }}
stringData: {}
{{- end }}
{{- end }}
