spring.application.name=sdfcc-backend-test

spring.jpa.hibernate.ddl-auto=create-drop

# Datasource is overridden at runtime by Testcontainers @DynamicPropertySource
# These placeholders prevent Spring from failing at startup before the override is applied
spring.datasource.url=jdbc:postgresql://localhost:5432/sdfcc
spring.datasource.username=sdfcc
spring.datasource.password=sdfcc
spring.jpa.open-in-view=true
spring.jpa.show-sql=true


#otel.service.name=${spring.application.name}
#otel.resource.attributes=service.namespace=sdfcc,deployment.environment=${DEPLOYMENT_ENVIRONMENT:local}
#otel.traces.exporter=${OTEL_TRACES_EXPORTER:otlp}
#otel.metrics.exporter=${OTEL_METRICS_EXPORTER:otlp}
#otel.logs.exporter=${OTEL_LOGS_EXPORTER:otlp}
#otel.exporter.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317}
#otel.exporter.otlp.protocol=${OTEL_EXPORTER_OTLP_PROTOCOL:grpc}
#otel.metric.export.interval=${OTEL_METRIC_EXPORT_INTERVAL:15000}
#
#otel.instrumentation.common.default-enabled=true
#otel.instrumentation.jdbc.enabled=true
#otel.instrumentation.spring-webmvc.enabled=true
#otel.instrumentation.spring-web.enabled=true
#otel.instrumentation.logback-appender.enabled=true
#
#logging.pattern.level=%5p [trace_id=%X{trace_id:-},span_id=%X{span_id:-}]


### Spring Security
jwt.issuer=sdfcc-backend-test
jwt.expiration-hours=1
jwt.signing-key=d57c8a078cc423d0f30364148098195543acb4b96cad76f1c443b0dc56559bc1
