spring.application.name=sdfcc-backend-localtesting


spring.jpa.hibernate.ddl-auto=update


#spring.datasource.url=${DATABASE_URL}
#spring.datasource.username=${DATABASE_USERNAME}
#spring.datasource.password=${DATABASE_PASSWORD}
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#spring.jpa.open-in-view=false
#spring.jpa.show-sql=false

### Spring Security
#jwt.issuer=${JWT_ISSUER:sdfcc-backend}
#jwt.expiration-hours=${JWT_EXPIRATION_HOURS:1}
#jwt.signing-key=${JWT_SIGNING_KEY:REPLACE_ME_WITH_A_STRONG_KEY}
